name: Recover Private Key

on:
  workflow_dispatch:

jobs:
  recovery:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run ECDSA-Bazooka with Docker
        run: |
          docker run --rm -v "$PWD:/data" ghcr.io/zee-cpu/ecdsa-bazooka -i /data/my_signatures.txt -v | tee output.log

      - name: Upload result
        uses: actions/upload-artifact@v4
        with:
          name: recovery-output
          path: output.log
